# Default config is at repo:
# learning-projects/python/mangadex-dl/config.toml

# api endpoints, change if needed
api_root = "https://api.mangadex.org"
report_root = "https://api.mangadex.network/report"

[save]
root = "mdex_save"          # where all chapters are saved
max_title_length = 60       # set to 0 (or lower) for unlimited

[images]
zero_padding = 3            # consider updating this for large chapters
use_datasaver = false
download_method = "curl"    # will fallback to requests if needed
max_retries = 5

[cli]
options_per_row = 3
results_per_page = 10
